config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :bins
  root 'articles#new'

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :bins
end

app/models/bin.rb
class Bin < ActiveRecord::Base
    belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def createBin
    @bin = @article.bins.create(bin_params)
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:author, :title)
      # params.fetch(:article, {})
    end

    def bin_params
      params.require(:article).permit(:text, :image_file_name, :image_content_type, :image_file_size, :image_updated_at)
    end
end

app/controllers/bins_controller.rb
class BinsController < ApplicationController
  before_action :set_bin, only: [:show, :edit, :update, :destroy]

  # GET /bins
  # GET /bins.json
  def index
    @bins = Bin.all
  end

  # GET /bins/1
  # GET /bins/1.json
  def show
    @article = Article.find(params[:id])
    @bins = @article.bins;
  end

  # GET /bins/new
  def new
    @article = Artifle.find(params[:id])
    @bin = @article.bins.new;
  end

  # GET /bins/1/edit
  def edit
  end

  # POST /bins
  # POST /bins.json
  def create
    @bin = Bin.new(bin_params)

    respond_to do |format|
      if @bin.save
        format.html { redirect_to @bin, notice: 'Bin was successfully created.' }
        format.json { render :show, status: :created, location: @bin }
      else
        format.html { render :new }
        format.json { render json: @bin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bins/1
  # PATCH/PUT /bins/1.json
  def update
    respond_to do |format|
      if @bin.update(bin_params)
        format.html { redirect_to @bin, notice: 'Bin was successfully updated.' }
        format.json { render :show, status: :ok, location: @bin }
      else
        format.html { render :edit }
        format.json { render json: @bin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bins/1
  # DELETE /bins/1.json
  def destroy
    @bin.destroy
    respond_to do |format|
      format.html { redirect_to bins_url, notice: 'Bin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bin
      @bin = Bin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bin_params
      params.require(:bin, :type).permit(:text, :image_file_name, :image_content_type, :image_file_size, :image_updated_at)
    end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  def default
  end

  def home
    render 'templates/default'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bins_helper.rb
module BinsHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, article, class: "index_title"%></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="new">
  <%= link_to 'New Article', new_article_path %>
</div>

app/views/articles/new.html.erb
<div class="popup">
    <h1>Create a new Article</h1>
    <%= form_for @article, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
      <%= f.text_field :title, placeholder: "title", class: "title" %>
      <%= f.text_field :author, placeholder: "author", class: "author" %>
      <%= f.submit "create", class:"submit" %>
    <% end %>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @article.title %><small><%= @article.author %></small></h1>
<div class="content">
    <div class="new">
        <div class="fab">
            <p>+</p>
        </div>
        <div class="options">
            <i id="img" class="fa fa-file-image-o" aria-hidden="true"></i>
            <i id="text" class="fa fa-file-text-o" aria-hidden="true"></i>
            <i id="excel" class="fa fa-file-excel-o" aria-hidden="true"></i>
            <i id="video" class="fa fa-file-video-o" aria-hidden="true"></i>
            <i id="code" class="fa fa-file-code-o" aria-hidden="true"></i>
        </div>
    </div>
    <div class="preview">
        <!-- <h2>Text</h2> -->
        <%= render :partial => "text_form" %>
    </div>
</div>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/bins/_form.html.erb
<%= form_for(@bin) do |f| %>
  <% if @bin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bin.errors.count, "error") %> prohibited this bin from being saved:</h2>

      <ul>
      <% @bin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bins/edit.html.erb
<h1>Editing Bin</h1>

<%= render 'form' %>

<%= link_to 'Show', @bin %> |
<%= link_to 'Back', bins_path %>

app/views/bins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bins</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bins.each do |bin| %>
      <tr>
        <td><%= link_to 'Show', bin %></td>
        <td><%= link_to 'Edit', edit_bin_path(bin) %></td>
        <td><%= link_to 'Destroy', bin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bin', new_bin_path %>

app/views/bins/new.html.erb
<div class="options">
    <h1>Create a new bin</h1>
    <%= form_for @bin, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
      <%= f.text_field :type, placeholder: "type", class: "type" %>
      <%= f.text_field :text, placeholder: "text", class: "text" %>
      <%= f.submit "create", class:"submit" %>
    <% end %>
</div>

<%= link_to 'back', bins_path %>

app/views/bins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bin_path(@bin) %> |
<%= link_to 'Back', bins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scribe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300,400italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <script src="https://use.fontawesome.com/7361d89f17.js"></script>
  <script   src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
</head>
<body>

<%= yield %>

</body>
</html>